apiVersion: v1
kind: PersistentVolume 
metadata:
  name: buildpacks-source-pv-1
spec:
  storageClassName: manual 
  capacity: 
    storage: 500Mi
  accessModes: 
    - ReadWriteOnce
  nfs: 
    path: "/nfs/share/nfs-client/buildpack-test"
    server: 192.168.101.110
