apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildpacks-source-pvc-1
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
